### ISSUE TITLE
Capitalization inconsistent in units

### ISSUE THREAD

**Issue by ibell** [CoolProp/GUI#11]
Can you please use a consistent capitalization scheme in the Settings panel?  I prefer first character capitalized and then subsequent characters not capitalized.

**Comment by mayersre** [comment]
Oh,

I applied german syntax to english semantics ;)
will fix it

Am 02.04.2015 um 07:02 schrieb Ian Bell:

**Comment by mayersre** [comment]
fixed in last commit
