### ISSUE TITLE
Crash on File->Quit

### ISSUE THREAD

**Issue by ibell** [CoolProp/GUI#19]
I see this on the console when I click Quit.. in the menu

```
Fatal Python error: PyEval_RestoreThread: NULL tstate
```

**Comment by ibell** [comment]
Fixed in the release, still crashes when run from source.

**Comment by mayersre** [comment]
I added a leave method with a destructor in the main, that should fix it, please try

**Comment by mayersre** [comment]
reproduced and fixed ...
call self made leave destructor instead of builtin quit on close ... committed and pushed
