### ISSUE TITLE
tkinter import broken on py2.7

### ISSUE THREAD

**Issue by ibell** [CoolProp/GUI#6]
According to https://docs.python.org/2/library/tkinter.html  ::

`Note Tkinter has been renamed to tkinter in Python 3`

and when I try to run `cpgui.py` I get the error 

```
Traceback (most recent call last):
  File "cpgui.py", line 11, in <module>
    from tkinter import filedialog, simpledialog
ImportError: No module named tkinter
```

my python

```
C:\Users\Belli\Documents\Code\CoolProp-GUI>python
Python 2.7.6 |Continuum Analytics, Inc.| (default, May 27 2014, 15:00:33) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io and https://binstar.org
```

**Comment by ibell** [comment]
Or a better solution - if when you run cpgui.py your python is 2.x, error out with a message that you can't use python 2.x @jowr - any input?

**Comment by mayersre** [comment]
I added a message box and consle output that Python 3 is required

**Comment by jowr** [comment]
Hi, are you sure that this works? 

```
$ python cpgui.py 
  File "cpgui.py", line 187
    print "Coolprop GUI requires Python 3 or later!"
                                                   ^
SyntaxError: Missing parentheses in call to 'print'
$ python --version
Python 3.4.3 :: Continuum Analytics, Inc.
```

**Comment by jowr** [comment]
Nice, we just committed the same change in the same file https://github.com/CoolProp/GUI/commit/06081854e6eaf47f8d5f89b3c00b55a0d5d2bf6f
