### ISSUE TITLE
pip URL

### ISSUE THREAD

**Issue by jowr** [CoolProp/GUI#9]
Hi, is there a specific reason to use the development server for Python binaries in https://github.com/CoolProp/GUI/blob/master/requirements.txt#L1 ? We have some trouble with that machine since it is cheap hosting service and we regularly hit the capcaity limits. Therefore I would like to move as much traffic as possible to the official download directories on SourceForge and pypi.

**Comment by mayersre** [comment]
No, no special reason, you can remove the line if you want.

**Comment by mayersre** [comment]
actually GUI works even with cp 4.2.5

**Comment by jowr** [comment]
That is great news. It would be nice, if you could remove the link. Thanks.

**Comment by mayersre** [comment]
ok, done
